services:
  postgres-service:
    image: 'postgres:16.6'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  spring-boot-react:
    container_name: spring-boot
    environment:
      - APP_PROFILE=${APP_PROFILE}
      - APP_ADMIN_EMAIL=${APP_ADMIN_EMAIL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-service:${DB_PORT}/${DB_NAME}
    restart: no
    ports:
      - '8080:8080'
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres-service

volumes:
  postgresql-data:
