services:
  postgres:
    image: 'postgres:16.6'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
  spring-boot-react-fullstack:
    container_name: spring-boot
    env_file: "./src/main/resources/.env"
    #environment:
    #  SPRING_APPLICATION_JSON: '{
    #    "spring.datasource.url" : "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}",
    #  }'
    #environment:
      #SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_NAME}:${DB_PORT}/${DB_NAME}
    #  - APP_PROFILE=${APP_PROFILE}
    #  - APP_ADMIN_EMAIL=${APP_ADMIN_EMAIL}
    ##  - DB_NAME=${DB_NAME}
    #  - DB_USER=${DB_USER}
    #  - DB_PASSWORD=${DB_PASSWORD}
    #  - DB_PORT=${DB_PORT}
    restart: on-failure
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./Dockerfile

