app:
  admin:
    email: ${APP_ADMIN_EMAIL}
spring:
  datasource:
    #driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
  profiles:
    active: ${APP_PROFILE}
  output:
    ansi:
      enabled: always
