app:
  admin:
    email: "gendalf-dev-admin@white.com"
spring:
  application:
    name: web-dev
  datasource:
    password: ${DB_PASSWORD:web}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:web}
    username: ${DB_USER:web}
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
