app:
  admin:
    email: ${APP_ADMIN_EMAIL}
spring:
  application:
    name: web-prod
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
  devtools:
    add-properties: false
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
